% Input date and time
Year=input('Year: ')
Month=input('Month: ')
Day=input('Day: ')
Hour=input('Hour: ')
Minute=input('Minute: ')
Second=input('Second: ')
Millisecond=input('Millisecond: ')
entered=datetime(Year,Month,Day,Hour,Minute,Second,Millisecond)% Get date and time by input values
disp(datetime(entered,"Format","dd-MMM-uuuu HH:mm:ss.SSS z"))% Format date and time
disp(datetime(entered,"Format","uuuu-MM-dd'T'HH:mm:ss.SSS"))
disp('Era: '+string(entered,"G")+' ('+string(entered,"GGGG")+')')
disp('Year: '+string(entered,"y"))
disp('ISO Year: '+string(entered,"u"))
disp('Quarter: '+string(entered,"Q")+' ('+string(entered,"QQQQ")+')')
disp('Month: '+string(entered,"M")+' - '+string(entered,"MMM")+' ('+string(entered,"MMMM")+')')
disp('Week of Month: '+string(entered,"W"))
disp('Day of month: '+string(entered,"d"))
disp('Day of Year: '+string(entered,"D"))
disp('Day of Week: '+string(entered,"e")+' ('+string(entered,"eeee")+')')
disp('Weekday: '+string(entered,"e")+' - '+string(entered,"eee")+' ('+string(entered,"eeee")+')')
disp('Hour: '+string(entered,"H")+' ('+string(entered,"h a")+')')
disp('Minute: '+string(entered,"m"))
disp('Second: '+string(entered,"s")+' (Milliseconds: '+string(entered,"SSS")+')')
disp('Time Zone: '+string(entered,"z"))
disp('Time Zone Offset: '+string(entered,"XXXXX"))
% Get current date and time
currentdt=datetime("now")% Get date and time by input values
disp(datetime(currentdt,"Format","dd-MMM-uuuu HH:mm:ss.SSS z"))% Format date and time
disp(datetime(currentdt,"Format","uuuu-MM-dd'T'HH:mm:ss.SSS"))
disp('Current Era: '+string(currentdt,"G")+' ('+string(currentdt,"GGGG")+')')
disp('Current Year: '+string(currentdt,"y"))
disp('Current ISO Year: '+string(currentdt,"u"))
disp('Current Quarter: '+string(currentdt,"Q")+' ('+string(currentdt,"QQQQ")+')')
disp('Current Month: '+string(currentdt,"M")+' - '+string(currentdt,"MMM")+' ('+string(currentdt,"MMMM")+')')
disp('Current Week of Month: '+string(currentdt,"W"))
disp('Current Day of month: '+string(currentdt,"d"))
disp('Current Day of Year: '+string(currentdt,"D"))
disp('Current Day of Week: '+string(currentdt,"e")+' ('+string(currentdt,"eeee")+')')
disp('Current Weekday: '+string(currentdt,"e")+' - '+string(currentdt,"eee")+' ('+string(currentdt,"eeee")+')')
disp('Current Hour: '+string(currentdt,"H")+' ('+string(currentdt,"h a")+')')
disp('Current Minute: '+string(currentdt,"m"))
disp('Current Second: '+string(currentdt,"s")+' (Milliseconds: '+string(currentdt,"SSS")+')')
disp('Current Time Zone: '+string(currentdt,"z"))
disp('Current Time Zone Offset: '+string(currentdt,"XXXXX"))
